In [9]:
import pandas as pd

In [12]:
a = pd.read_csv('쥬피터 소스파일/17~19 아파트매매 자료.csv')
.head()

시군구     번지   본번  부번      단지명  전용면적(㎡)    계약년월  계약일 거래금액(만원)  층  \
0  부산광역시 강서구 녹산동  262-1  262   1  유나베네스1차  72.5242  201710    1   20,500  6   
1  부산광역시 강서구 녹산동  262-1  262   1  유나베네스1차  72.5242  201710    2   20,500  3   
2  부산광역시 강서구 녹산동  262-1  262   1  유나베네스1차  62.2475  201710   24   19,000  5   
3  부산광역시 강서구 녹산동  262-1  262   1  유나베네스1차  62.2475  201710   25   18,800  2   
4  부산광역시 강서구 녹산동  262-1  262   1  유나베네스1차  72.5242  201710   26   20,800  2   

   건축년도           도로명  
0  2017  화전산업대로 272-9  
1  2017  화전산업대로 272-9  
2  2017  화전산업대로 272-9  
3  2017  화전산업대로 272-9  
4  2017  화전산업대로 272-9

# 과제1
- np 변수에 실수 5개가 들어간 리스트를 저장하시오
- flotV 리스트 안에 np 리스트를 3개 넣으시오
- 첫 번째 flotV의 리스트를 "그냥"으로 변경하시오

In [14]:
import numpy as np
b = [1, 2, 3, 4, 5]

floatV = [b, b, b]
print(floatV)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


# 과제2
- numpy를 import 하시오
- numpy를 이용해서 5개의 실수를 가지는 배열을 생성하시오
- 생성한 배열의 합을 구하시오
- 생성한 배열의 표준편차를 구하시오

In [27]:
import numpy as np

c= np.array([1, 2, 3, 4, 5])

print(c.sum())
print(c.std())

15
1.4142135623730951


# 과제3
- np.zeros를 활용해서 2차원 배열을 생성하시오
- np.zeros를 활용해서 3차원 배열을 생성하시오

In [38]:
# 2차원 배열
c = np.zeros((2,3), dtype = 'i')
print(c)

[[0 0 0]
 [0 0 0]]


In [40]:
# 3차원 배열
c = np.zeros((3,3), dtype = 'i') #행의 개수가 차원의 개수
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 과제4
- pandas를 import 하시오
- pandas를 이용해서 데이터 Series를 생성하시오
- pandas를 이용해서 데이터 프레임을 생성하시오

In [42]:
import pandas as pd
pandas_series = pd.Series([200, 300, 400], index = ['아', '이', '우'])
print(pandas_series)

아    200
이    300
우    400
dtype: int64


In [49]:
import pandas as pd
pandas_DataFrame = pd.DataFrame([200, 300, 400], index = ['아', '이', '우'], columns = ['모르지'])
print(pandas_DataFrame)

   모르지
아  200
이  300
우  400
